version: "3.6"

services:
  robo4j:
    container_name: robo4j
    image: robo4j_j11:latest
    ports:
      - "8042:8042"

    tty: true
    networks:
      - simulation

networks:
  simulation:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv4: "true"